id = "just"
name = "Justfile"
description = "Justfile syntax highlighting"
version = "0.1.2"
schema_version = 1
authors = ["Jack T. <jack@jackt.space>"]
repository = "https://github.com/jackTabsCode/zed-just"

[grammars.just]
repository = "https://github.com/IndianBoy42/tree-sitter-just"
commit = "f676df848d59ca50f56dd3a534a4472bcf389024"
